### PR TITLE
Join table

### PR DESCRIPTION
**Pull request by akhror-valiev**
##Summary
- Prepared complex queries that answered analytical questions.
- 
1a
2a
3a
4a
5a
6a
7a
8a
9a
Used primary key & foreign key mechanisms for joining tables.

### CODE REVIEW

**Review by Ghiftee — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello @akhror-valiev  👋🏽 

Good job working on the project so far! 
To highlight 👍🏽 
✔️ You added all data and queries
✔️ Queries are successful
✔️ You added screenshots

However, there are some issues that you need to work on to go to the next project but you are almost there!



## Required Changes ♻️
- [ ] Kindly fill out the ```Getting started```, ```show your support```, ```Acknowledgement``` and ```FAQ``` sections of your README as this would make it more professional.
- [ ] Also, your MIT license is broken, kindly fix it.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Review by christianbiring1 — CHANGES_REQUESTED** [review]
Hi @akhror-valiev , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
# STATUS: REQUEST CHANGES :tada: 


 ## Highlights
:heavy_check_mark: You added all data and queries
:heavy_check_mark: Queries are successful
:heavy_check_mark: You added screenshots

 ## Required Changes ♻️
- [ ] `KINDLY, AS SUGGESTED BY THE PREVIOUS REVIEWER, MAKE SURE YOU COMPLETE THOSE MISSINGS POINTS IN YOUR README BEFORE RESUBMITTING FOR ANOTHER REVIEW.`

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by akhror-valiev** [comment]
@christianbiring1 I have already changed it, please pay attention closely, and explain to me it as clearly, even your project's readme.md file is wrong

**Comment by christianbiring1** [comment]
> * Kindly fill out the `Getting started`, `show your support`, `Acknowledgement` and `FAQ` sections of your README as this would make it more professional.
> * [ ]  Also, your MIT license is broken, kindly fix it.

Hey @akhror-valiev 
As suggested by the previous reviewer, for review consistency you need to implement the changes you were required to do before you resubmit your project for another review. 
Here's what the reviewer suggested  :point_down: 
- [ ] Kindly fill out the `Getting started`, `show your support`, `Acknowledgement` and `FAQ` sections of your README as this would make it more professional.
- [ ] Also, your MIT license is broken, kindly fix it.

**Comment by akhror-valiev** [comment]
I do not understand why reviewers pay attention only readme.me file rather than a problem in the project. I think it is an easier way to show himself/herself as he/she worked as a reviewer. I know README.md is also important but it is not essential as the project's requirement, And also you can show bigger mistakes reademe.md others should be acceptable.

**Comment by akhror-valiev** [comment]
@christianbiring1, it is easy to talk, go to your readme file and check your MIT license link is also broken, even yours is not the right version.

**Comment by akhror-valiev** [comment]
@christianbiring1 if you are too good, give me an example of how to fill good readme.md file

**Comment by christianbiring1** [comment]
> @christianbiring1, it is easy to talk, go to your readme file and check your MIT license link is also broken, even yours is not the right version.

Every time the learning materials and the general requirements for the project are updated as well, so what you are being asked today it might be possible to be updated three or 6 months later. 
image
You can find the updated template of the README [here](https://github.com/microverseinc/readme-template)

**Comment by akhror-valiev** [comment]
> > @christianbiring1, it is easy to talk, go to your readme file and check your MIT license link is also broken, even yours is not the right version.
> 
> Every time the learning materials and the general requirements for the project are updated as well, so what you are being asked today it might be possible to be updated three or 6 months later. image You can find the updated template of the README [here](https://github.com/microverseinc/readme-template)

mine is same as the above!

**Review by bimbolabuari — COMMENTED** [review]
Hello @akhror-valiev  👋,

_This is an additional review as a result of the second opinion request._

- Kudos on implementing the project requirement for this milestone 👍 
  - Reviews are constructive feedback(s) in order to make our project cleaner and professional, README are as important as the project, A README is often the first item a visitor will see when visiting your repository, it entails the project description, information, manual etc imagine a new book without a nice and appealing cover, I am sure you won't like to open it and check the book content right? 😉 
  
   - I would love us to be professional when receiving and giving feedback, CR(s) are following specific guidelines in order to give reviews.
   
Kindly implement the changes and re-submit for approval 🙂 

Keep rocking 🚀!

**Comment by akhror-valiev** [comment]
> Hello @akhror-valiev 👋,
> 
> _This is an additional review as a result of the second opinion request._
> 
> * Kudos on implementing the project requirement for this milestone 👍
>   
>   * Reviews are constructive feedback(s) in order to make our project cleaner and professional, README are as important as the project, A README is often the first item a visitor will see when visiting your repository, it entails the project description, information, manual etc imagine a new book without a nice and appealing cover, I am sure you won't like to open it and check the book content right? 😉
>   * I would love us to be professional when receiving and giving feedback, CR(s) are following specific guidelines in order to give reviews.
> 
> Kindly implement the changes and re-submit for approval 🙂
> 
> Keep rocking 🚀!

ok very good 👍

**Review by sumairq — COMMENTED** [review]
Hi @akhror-valiev , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, where the pull request branch has conflicts that must be resolved.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by sumairq — APPROVED** [review]
### Hi @akhror-valiev , 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
